excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://irwinwilliams.github.io
title: Irwin Williams, a blog
email: irwin.williams@gmail.com
author: Irwin Williams
description: This is a blog. It's Irwin's.
paginate: 20
google_analytics: UA-26580532-3
permalink: /:year/:month/:day/:title/
theme: "henry"
# Jekyll Plugins Necessary for GH Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
 - docker-compose-publish.yml
 - docker-compose.yml
 - firebase.json
 - .idea/
